name: fibonacci_matrix
description: A Fibonacci's matrix project made with flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  lottie: ^1.4.3

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  freezed: ^2.2.0
  build_runner:
  flutter_launcher_icons_maker: ^0.10.2
  injectable_generator: ^1.5.4
  bloc_test: ^9.1.0

flutter_icons:
  android: true
  windows: true
  web: true
  image_path: "assets/icons/icon.png"


flutter:
  #generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #Assets
  assets:
    - assets/icons/