name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  test:
    name: running tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: flutter test
  build:
    name: 🚀 Build Web on main
      needs: [test]
    env:
      my_secret: ${{secrets.PAT}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.1'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web lib/main.dart --release
      - run: |
          cd build/web
          git init
          git config --global user.email carlos.hernandez3@catolica.edu.sv
          git config --global user.name g14wx
          git status
          git remote add origin https://${{env.my_secret}}@github.com/fibonacci_matrix.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update web"
          git push origin gh-pages -f