on:
#  pull_request:
#    branches:
#      - main
#      - master
#      - develop
  push:
    branches:
      - main
name: "🚀 📱 Build App mobile for android"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: flutter test
  build:
    name: Build & Release
      needs: [test]
    runs-on: ubuntu-latest #macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.1'
      - run: flutter pub get
      - run: flutter build apk lib/main.dart --split-per-abi
      #- run: |
      #    flutter build ios --no-codesign
      #   cd build/ios/iphoneos
      #   mkdir Payload
      #   cd Payload
      #   ln -s ../Runner.app
      #   cd ..
      #   zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.PAT }}